name: ddfguiderate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  background_fetch: ^1.3.8
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  cached_network_image: ^3.3.1
  fl_chart: ^0.71.0
  url_launcher: ^6.2.4
  share_plus: ^11.0.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 